### ISSUE TITLE
Add OpenAPI Specification

### ISSUE THREAD

**Issue by kakkoyun** [observatorium/api#139]
It would be super useful to have these specifications to generate SDKs and client codes
https://swagger.io/specification/

**Comment by esnible** [comment]
Now that Observatorium-API (optionally) supports receiving OpenTelemetry traces, the API spec for traces might be useful here.

The Swagger for trace ingestion can be generated by using https://github.com/open-telemetry/opentelemetry-proto and doing `make gen-openapi`.

Two difficulties:
- Observatorium only supports traces if the `--traces.write.endpoint` flag is supplied
- The version of traces supported is dependent on the OTel version, which [is dependent on how Observatorium is deployed](https://github.com/observatorium/observatorium/blob/main/configuration/components/tracing.libsonnet#L11) rather than being compiled into the source.

cc @pavolloffay
